#!/usr/bin/env python3
"""Generate per-topic README.md files from question sources.

Run from anywhere: python scripts/build_topic_readmes.py
Also refreshes the <!-- topic-toc:start --> ... <!-- topic-toc:end --> block in the repo README.
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# (display name for H1, directory under repo, glob relative to that directory)
TOPICS: list[tuple[str, str, str]] = [
    ("Common", "common", "questions/*.md"),
    ("Python", "python", "questions/*.md"),
    ("Flask", "flask", "questions/*.md"),
    ("React", "react", "questions/*.md"),
    ("SQL", "sql", "questions/*.md"),
    ("Cybersecurity", "cybersecurity", "s*.md"),
]

ROOT_TOC_LINKS: list[tuple[str, str]] = [
    ("Common", "common"),
    ("Python", "python"),
    ("Flask", "flask"),
    ("React", "react"),
    ("SQL", "sql"),
    ("Cybersecurity", "cybersecurity"),
]

STUB_THRESHOLD = 15
GENERATOR_BLURB = (
    "_Auto-generated by `scripts/build_topic_readmes.py`. "
    "Edit the source `.md` files in this topic and re-run the script._"
)


def heading_anchor(heading: str) -> str:
    """Approximate GitHub heading IDs (ASCII, punctuation stripped)."""
    h = unicodedata.normalize("NFKD", heading)
    h = h.encode("ascii", "ignore").decode("ascii")
    h = h.lower().strip()
    h = h.replace("_", "-")
    h = re.sub(r"[^a-z0-9\s-]", "", h)
    h = re.sub(r"\s+", "-", h)
    h = re.sub(r"-+", "-", h)
    return h.strip("-")


def parse_question_file(text: str, fallback_title: str) -> tuple[str, str]:
    lines = text.splitlines()
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i >= len(lines):
        return fallback_title, ""

    first = lines[i].strip()
    if first.startswith("#"):
        title = first.lstrip("#").strip()
        body_lines = lines[i + 1 :]
    elif first.startswith("Q."):
        title = first[2:].strip()
        body_lines = lines[i + 1 :]
    else:
        title = fallback_title
        body_lines = lines[i:]

    body = "\n".join(body_lines).strip()
    return title, body


def wrap_answer(body: str) -> str:
    if len(body) < STUB_THRESHOLD:
        inner = "*TODO: draft answer.*"
    else:
        inner = body
    return (
        "<details>\n"
        "<summary>Reveal answer</summary>\n"
        "\n"
        f"{inner}\n"
        "\n"
        "</details>"
    )


def build_topic_readme(display_name: str, topic_dir: str, pattern: str) -> str:
    base = REPO_ROOT / topic_dir
    paths = sorted(base.glob(pattern), key=lambda p: p.name.lower())
    lines: list[str] = [
        f"# {display_name} — interview questions",
        "",
        GENERATOR_BLURB,
        "",
        "## Table of contents",
        "",
    ]

    toc_entries: list[tuple[int, str, str]] = []
    sections: list[str] = []

    for n, path in enumerate(paths, start=1):
        raw = path.read_text(encoding="utf-8")
        title, body = parse_question_file(raw, path.stem.replace("-", " ").replace("_", " "))
        heading_text = f"{n}. {title}"
        slug = heading_anchor(heading_text)
        toc_entries.append((n, title, slug))

        section_parts = [
            f"#### {heading_text}",
            "",
            wrap_answer(body),
            "",
            "**[⬆ Back to top](#table-of-contents)**",
            "",
            "---",
            "",
        ]
        sections.append("\n".join(section_parts))

    for n, title, slug in toc_entries:
        lines.append(f"- [{n}. {title}](#{slug})")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.extend("\n".join(sections).rstrip().splitlines())
    lines.append("")

    return "\n".join(lines)


def write_topic_readmes() -> None:
    for display_name, topic_dir, pattern in TOPICS:
        out = REPO_ROOT / topic_dir / "README.md"
        out.write_text(build_topic_readme(display_name, topic_dir, pattern), encoding="utf-8")
        print(f"Wrote {out.relative_to(REPO_ROOT)}")


def refresh_root_toc() -> None:
    readme = REPO_ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    toc_body = "\n".join(f"- [{label}]({path}/README.md)" for label, path in ROOT_TOC_LINKS)
    block = f"<!-- topic-toc:start -->\n{toc_body}\n<!-- topic-toc:end -->"
    if "<!-- topic-toc:start -->" in text and "<!-- topic-toc:end -->" in text:
        text = re.sub(
            r"<!-- topic-toc:start -->.*?<!-- topic-toc:end -->",
            block,
            text,
            count=1,
            flags=re.DOTALL,
        )
    else:
        raise RuntimeError(
            "README.md must contain <!-- topic-toc:start --> and <!-- topic-toc:end --> markers."
        )
    readme.write_text(text, encoding="utf-8")
    print(f"Updated {readme.relative_to(REPO_ROOT)} topic TOC block")


def main() -> None:
    write_topic_readmes()
    refresh_root_toc()


if __name__ == "__main__":
    main()
